services:
  - type: web
    name: TwinQueryClassifier-App
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.headless true
    autoDeploy: true
